# Generated by Django 4.2.2 on 2023-06-20 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoRecoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('localidad', models.CharField(choices=[('Usaquén', 'Usaquén'), ('Chapinero', 'Chapinero'), ('Santa Fe', 'Santa Fe'), ('San Cristóbal', 'San Cristóbal'), ('Usme', 'Usme'), ('Tunjuelito', 'Tunjuelito'), ('Bosa', 'Bosa'), ('Kennedy', 'Kennedy'), ('Fontibón', 'Fontibón'), ('Engativá', 'Engativá'), ('Suba', 'Suba'), ('Barrios Unidos', 'Barrios Unidos'), ('Teusaquillo', 'Teusaquillo'), ('Los Mártires', 'Los Mártires'), ('Antonio Nariño', 'Antonio Nariño'), ('Puente Aranda', 'Puente Aranda'), ('La Candelaria', 'La Candelaria'), ('Rafael Uribe Uribe', 'Rafael Uribe Uribe'), ('Ciudad Bolívar', 'Ciudad Bolívar')], max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('bicicleta', models.PositiveIntegerField(blank=True, null=True)),
                ('motocicleta', models.PositiveIntegerField(blank=True, null=True)),
                ('automovil13', models.PositiveIntegerField(blank=True, null=True)),
                ('automovil14', models.PositiveIntegerField(blank=True, null=True)),
                ('automovil15', models.PositiveIntegerField(blank=True, null=True)),
                ('camioneta16', models.PositiveIntegerField(blank=True, null=True)),
                ('camioneta17', models.PositiveIntegerField(blank=True, null=True)),
                ('camioneta18', models.PositiveIntegerField(blank=True, null=True)),
                ('camioneta19', models.PositiveIntegerField(blank=True, null=True)),
                ('especiales', models.PositiveIntegerField(blank=True, null=True)),
                ('recoleccion', models.BooleanField(default=False)),
            ],
        ),
    ]
