# Generated by Django 4.2.2 on 2023-08-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotidai_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntorecoleccion',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='puntorecoleccion',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
