# Generated by Django 4.2.2 on 2023-08-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotidai_api', '0002_alter_puntorecoleccion_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntorecoleccion',
            name='total_llantas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
