# Generated by Django 4.2.2 on 2023-08-26 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecotidai_api', '0003_puntorecoleccion_total_llantas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntorecoleccion',
            name='total_llantas',
        ),
    ]
